name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image and deploy to minikube
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/nodejs-app:latest .
          echo -n "verifying images:"
          docker images
          minikube cache add devopshint/nodejs-app:latest
          minikube image load devopshint/nodejs-app:latest
      - name: Deploy to minikube
        run: kubectl apply -f k8s-node-app.yaml
      - name: Delay for the container to be created
        run: sleep 15
      - name: Try the cluster again!
        run: kubectl get pods -A
      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-app --url
