name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image and deploy to minikube
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Esperar a que CoreDNS esté listo
        run: |
          kubectl wait --namespace kube-system \
            --for=condition=Ready pod -l k8s-app=kube-dns \
            --timeout=90s
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/nodejs-app:latest .
          echo -n "verifying images:"
          docker images
      - name: Deploy to minikube
        run: kubectl apply -f k8s-node-app.yaml
      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-app --url
